version: "3.7"

services:
    workshop-database:
        container_name: workshop_mariadb
        build:
            context: ./database
        environment:
            - MYSQL_DATABASE=${DATABASE_NAME}
            - MYSQL_USER=${DATABASE_USER}
            - MYSQL_PASSWORD=${DATABASE_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
        volumes:
            - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./datalogs/data:/var/lib/mysql
        networks:
            - workshop-database
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - '3308:3307'
        environment:
            PMA_HOST: workshop-database
        networks:
            - workshop-database   
    workshop-php:
        container_name: workshop_php_fpm
        build:
            context: ./php-fpm
        depends_on:
            - workshop-database
        volumes:
            - ../app:/var/www
        networks:
            - workshop-database
            - workshop-php
    workshop-nginx:
        container_name: workshop_nginx
        build:
            context: ./nginx
        volumes:
            - ../app:/var/www
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/sites/:/etc/nginx/sites-available
            - ./nginx/conf.d/:/etc/nginx/conf.d
            - ./logs:/var/log
        depends_on:
            - workshop-php
        networks:
            - workshop-php
        ports:
            - ${NGINX_PORT}:80
            - ${NGINX_HTTPS}:443
networks:
    workshop-database:
    workshop-php:
